--- 
title: "Formula 1 Season Report"
author: "Joao Lucas D. R. Hilgert"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a simple Formula 1 report."
always_allow_html: true
---

# Intro {-}

This is an online report to the 2022 Formula 1 Season.

```{r warning=FALSE, include=FALSE}
library(f1Package)
lapply(f1_reqPackages, require, character.only = TRUE) 

Sys.setlocale("LC_TIME", "English")
```

```{r include=FALSE}
round_var <- 1
target_year <- 2022
```

```{r include=FALSE}
# Grand Prix Rounds
url <- "http://ergast.com/api/f1/current"

temp <- xmlToList(rawToChar(GET(url)$content))

grandPrixRounds <- data.frame()
for(i in 1:(length(temp$RaceTable)-1)) {
  circuit_temp <- temp$RaceTable[i]
  
  row_temp <- cbind(
    as.numeric(circuit_temp$Race$.attrs["round"]),
    bind_rows(circuit_temp$Race[c(1,3)]),
    circuit_temp$Race$Circuit$CircuitName,
    bind_rows(circuit_temp$Race$Circuit$Location[1:2]),
    bind_rows(circuit_temp$Race$Circuit$Location$.attrs),
    circuit_temp$Race$.attrs["url"]
  ) %>%
    rename(
      CircuitName = "circuit_temp$Race$Circuit$CircuitName",
      Round = "as.numeric(circuit_temp$Race$.attrs[\"round\"])",
      url = 'circuit_temp$Race$.attrs["url"]'
      )
  
  grandPrixRounds <- rbind(grandPrixRounds, row_temp)
}

grandPrixRounds <- grandPrixRounds %>%
  mutate(pointsFirst = ifelse(
    Locality %in% c(
      "Imola",
      "Spielberg",
      "São Paulo"
    ),
    32,
    26
  )) %>%
  mutate(pointsSecond = ifelse(
    Locality %in% c(
      "Imola",
      "Spielberg",
      "São Paulo"
    ),
    25,
    20
  )) %>%
  mutate(pointsThird = ifelse(
    Locality %in% c(
      "Imola",
      "Spielberg",
      "São Paulo"
    ),
    21,
    15
  )) %>%
  mutate(lat = as.numeric(lat), long = as.numeric(long))
```



